name: Deploy DMT

on:
  workflow_dispatch:   # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy to Ethereum Mainnet
        run: npx hardhat run scripts/deploy-dmt.js --network mainnet
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
