name: Deploy DMT Token

on:
  workflow_dispatch:   # Manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # 4️⃣ Compile smart contracts
      - name: Compile contracts
        run: npx hardhat compile

      # 5️⃣ Deploy DMT token contract
      - name: Deploy DMT
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          BICONOMY_API_KEY: ${{ secrets.BICONOMY_API_KEY }}
        run: node scripts/deploy-dmt.js
